[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_THEME = "coHub"
  GO_VERSION = "1.20"

[context.production.environment]
  HUGO_ENV = "production"