[build]
  command = "hugo"
  publish = "public"

[build.environment]
  GO_VERSION = "1.20"
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[dev]
  framework = "hugo"
  targetPort = 1313